version: '2'
services:
  web:  
    build:
      dockerfile : Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    expose:
      - "8000"

  nginx:
    image: app/nginx:latest # nginx 서비스에서 사용할 도커 이미지
    ports:
      - "80:80"
    volumes:
      - .:/app
      - /app/nginx/nginx.conf:/etc/nginx/conf.d
    depends_on: # 서비스 간의 종속성 표현
      - web
